### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by tansaku**
Code of conduct for the whole community ...

### CODE REVIEW

**Comment by tansaku** [comment]
we'll need to create reporting guidelines to go here: https://www.agileventures.org/reporting-guidelines and grievance policy here: https://www.agileventures.org/grievance-policy

**Comment by ragesoss** [comment]
I like it. Straightforward, based on some well-tested CoCs, and it has an appropriate simple starting point for handling reports of bad behavior.

**Comment by tansaku** [comment]
great to hear that @ragesoss - it's the http://citizencodeofconduct.org/ template from GitHub that we're using here ...

**Comment by weedySeaDragon** [comment]
**Thanks for this!**  

My comment is about this wording in section **1. Purpose:**

       regardless of ..., and religion (or lack thereof).

Acknowledging the "or lack thereof" view is important. But putting it in parentheses sets it apart from all of those that 'have' religion and (IMHO) the parentheses minimize it and make it _lesser than_.  My suggestion is to use the wording `... , and religious views/beliefs.`

For me, this is important, but I don't want it to stop getting the CoC up.  If this isn't a simple resolution, I'd rather that it go up as is, and then this particular item addressed and resolved later.

**Comment by tansaku** [comment]
@weedySeaDragon - that change sounds good - you could also make that suggestion as a PR against https://github.com/stumpsyn/policies/blob/master/citizen_code_of_conduct.md so that other communities used that wording, but that won't slow us down here :-)

**Comment by tansaku** [comment]
@weedySeaDragon I think I've changed as per your suggestion ...

**Comment by weedySeaDragon** [comment]
Thanks, @tansaku .  That works for me.  Would be good to know if it's ok with others, of course. :-)

**Comment by FedericoEsparza** [comment]
@weedySeaDragon Good suggestion, Ashley. I think your change reflects the original intent with better wording.

**Pull request merged**
