### PR TITLE
57 add html styling

### LINKED ISSUE #57: incorrect linkage between AV premium pages and those in this repo
I note we're still a bit screwed up in that #websiteone is linking to premium mob and f2f pages with underscores (to pages that have the correct open/close HTML formatting) and that the pages PREMIUM_MOB.md and PREMIUM_F2F.md in the AV/AV repo are being copied over to premium-mob and premium-f2f (i.e. with hyphens) so updates there are not coming through to the actual pages that are linked into the site, and also those pages in AV/AV don't have the correct open/close HTML ...

### PR DESCRIPTION
**Pull request by mattwr18**
fixes #57

### CODE REVIEW

**Comment by mattwr18** [comment]
currently failing these tests:
```
should convert './PREMIUM_F2F.md' markdown to html (FAILED - 2)
should convert './PREMIUM_MOB.md' markdown to html (FAILED - 1)
```
maybe I have gone the wrong path on this one?

**Comment by tansaku** [comment]
hmm, looks like we may have a character we can't handle:

```
 got #<Encoding::UndefinedConversionError: "\xC2" from ASCII-8BIT to UTF-8> with backtrace:
```

Have had this before with unicode chars in the files I think ...

**Comment by mattwr18** [comment]
screenshot at 2018-11-26 14 01 45
screenshot at 2018-11-26 14 03 19
@tansaku here is the preview

**Comment by mattwr18** [comment]
@tansaku can we get this merged in? I was thinking that we could get them imported, check they look good, and then switch the hard-coded relative paths to point to the slug-friendly ones.

**Pull request merged**
